version: "3.3"
services:
    angular:
        image: angular:latest
        container_name: angular-1
        restart: always
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN
        ports:
            - 80:80
            - 443:443
